/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Siswa;

import model.User;

/**
 *
 * @author RIZAL
 */
public class DashboardSiswaPanel extends javax.swing.JPanel {

    private User user;
    
    /**
     * Creates new form DashboardSiswaPanel
     */
    public DashboardSiswaPanel() {
        initComponents();
    }

    public DashboardSiswaPanel(User user) {
        initComponents();
        this.user = user;
        txtWelcome.setText("Welcome, " + user.getUsername() + "!!!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWelcome = new javax.swing.JLabel();

        txtWelcome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtWelcome.setText("Selamat datang, siswa!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtWelcome)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtWelcome)
                .addContainerGap(455, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
