/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Siswa;

import controller.InvoiceController;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Invoice;

/**
 *
 * @author RIZAL
 */
public class PembayaranPanel extends javax.swing.JPanel {

    private SiswaDashboard siswaDashboard;
    private int studentId;

    /**
     * Creates new form PembayaranPanel
     */
    public PembayaranPanel(SiswaDashboard siswaDashboard, int studentId) {
        initComponents();
        this.siswaDashboard = siswaDashboard;
        this.studentId = studentId;
        tampilDataInvoice();
    }

    public void tampilDataInvoice() {
        InvoiceController controller = new InvoiceController();
        List<Invoice> invoiceList = controller.getAllStudentInvoice(studentId);

        String[] kolom = {"ID", "No", "Jumlah", "Tanggal Jatuh Tempo", "Status"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);

        int nomor = 1;
        for (Invoice inv : invoiceList) {
            Object[] row = {
                inv.getId(),
                nomor++,
                inv.getJumlah(),
                inv.getTanggalJatuhTempo(),
                inv.getStatus()
            };
            model.addRow(row);
        }

        tabelInvoice.getColumnModel().getColumn(0).setMinWidth(0);
        tabelInvoice.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelInvoice.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelInvoice = new javax.swing.JTable();
        btnBayar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Pembayaran");

        tabelInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelInvoice);

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(btnBayar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        int selectedRow = tabelInvoice.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data invoice dulu!");
            return;
        }

        String status = tabelInvoice.getValueAt(selectedRow, 4).toString();

        if (status.equalsIgnoreCase("lunas")) {
            JOptionPane.showMessageDialog(this, "Invoice sudah lunas!");
            return;
        }

        int invoiceId = Integer.parseInt(tabelInvoice.getValueAt(selectedRow, 0).toString());

        InvoiceController controller = new InvoiceController();
        Invoice invoice = controller.getInvoiceById(invoiceId);

        if (invoice != null) {
            FormPembayaranPanel form = new FormPembayaranPanel(siswaDashboard, invoiceId);
            CardLayout cl = (CardLayout) siswaDashboard.getPanelContent().getLayout();
            siswaDashboard.getPanelContent().add(form, "FormPembayaran");
            cl.show(siswaDashboard.getPanelContent(), "FormPembayaran");
        } else {
            JOptionPane.showMessageDialog(this, "Data invoice tidak ditemukan!");
        }
    }//GEN-LAST:event_btnBayarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelInvoice;
    // End of variables declaration//GEN-END:variables
}
